//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atc.Network.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Communication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Communication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atc.Network.Resource.Communication", typeof(Communication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Communication.
        /// </summary>
        public static string _Communication {
            get {
                return ResourceManager.GetString("_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting.
        /// </summary>
        public static string Disconnecting {
            get {
                return ResourceManager.GetString("Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnection.
        /// </summary>
        public static string Disconnection {
            get {
                return ResourceManager.GetString("Disconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoConnect.
        /// </summary>
        public static string DoConnect {
            get {
                return ResourceManager.GetString("DoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoDisconnect.
        /// </summary>
        public static string DoDisconnect {
            get {
                return ResourceManager.GetString("DoDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to disconnect the connection?.
        /// </summary>
        public static string DoYouWantToDisconnectTheConnection {
            get {
                return ResourceManager.GetString("DoYouWantToDisconnectTheConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint address.
        /// </summary>
        public static string EndpointAddress {
            get {
                return ResourceManager.GetString("EndpointAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnected.
        /// </summary>
        public static string Reconnected {
            get {
                return ResourceManager.GetString("Reconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting.
        /// </summary>
        public static string Reconnecting {
            get {
                return ResourceManager.GetString("Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to reconnect.
        /// </summary>
        public static string TryingToReconnect {
            get {
                return ResourceManager.GetString("TryingToReconnect", resourceCulture);
            }
        }
    }
}
