//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atc.Network.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atc.Network.Resource.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad destination.
        /// </summary>
        public static string IPStatusBadDestination {
            get {
                return ResourceManager.GetString("IPStatusBadDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad header.
        /// </summary>
        public static string IPStatusBadHeader {
            get {
                return ResourceManager.GetString("IPStatusBadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad option.
        /// </summary>
        public static string IPStatusBadOption {
            get {
                return ResourceManager.GetString("IPStatusBadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad route.
        /// </summary>
        public static string IPStatusBadRoute {
            get {
                return ResourceManager.GetString("IPStatusBadRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination host unreachable.
        /// </summary>
        public static string IPStatusDestinationHostUnreachable {
            get {
                return ResourceManager.GetString("IPStatusDestinationHostUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination network unreachable.
        /// </summary>
        public static string IPStatusDestinationNetworkUnreachable {
            get {
                return ResourceManager.GetString("IPStatusDestinationNetworkUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination port unreachable.
        /// </summary>
        public static string IPStatusDestinationPortUnreachable {
            get {
                return ResourceManager.GetString("IPStatusDestinationPortUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination prohibited.
        /// </summary>
        public static string IPStatusDestinationProhibited {
            get {
                return ResourceManager.GetString("IPStatusDestinationProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination scope mismatch.
        /// </summary>
        public static string IPStatusDestinationScopeMismatch {
            get {
                return ResourceManager.GetString("IPStatusDestinationScopeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination unreachable.
        /// </summary>
        public static string IPStatusDestinationUnreachable {
            get {
                return ResourceManager.GetString("IPStatusDestinationUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware error.
        /// </summary>
        public static string IPStatusHardwareError {
            get {
                return ResourceManager.GetString("IPStatusHardwareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMP error.
        /// </summary>
        public static string IPStatusIcmpError {
            get {
                return ResourceManager.GetString("IPStatusIcmpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resources.
        /// </summary>
        public static string IPStatusNoResources {
            get {
                return ResourceManager.GetString("IPStatusNoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet is too big.
        /// </summary>
        public static string IPStatusPacketTooBig {
            get {
                return ResourceManager.GetString("IPStatusPacketTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter problem.
        /// </summary>
        public static string IPStatusParameterProblem {
            get {
                return ResourceManager.GetString("IPStatusParameterProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source quench.
        /// </summary>
        public static string IPStatusSourceQuench {
            get {
                return ResourceManager.GetString("IPStatusSourceQuench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string IPStatusSuccess {
            get {
                return ResourceManager.GetString("IPStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out.
        /// </summary>
        public static string IPStatusTimedOut {
            get {
                return ResourceManager.GetString("IPStatusTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time exceeded.
        /// </summary>
        public static string IPStatusTimeExceeded {
            get {
                return ResourceManager.GetString("IPStatusTimeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTL expired.
        /// </summary>
        public static string IPStatusTtlExpired {
            get {
                return ResourceManager.GetString("IPStatusTtlExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTL reassembly time exceeded.
        /// </summary>
        public static string IPStatusTtlReassemblyTimeExceeded {
            get {
                return ResourceManager.GetString("IPStatusTtlReassemblyTimeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string IPStatusUnknown {
            get {
                return ResourceManager.GetString("IPStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized next header.
        /// </summary>
        public static string IPStatusUnrecognizedNextHeader {
            get {
                return ResourceManager.GetString("IPStatusUnrecognizedNextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string NetworkQualityCategoryTypeExcellent {
            get {
                return ResourceManager.GetString("NetworkQualityCategoryTypeExcellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        public static string NetworkQualityCategoryTypeFair {
            get {
                return ResourceManager.GetString("NetworkQualityCategoryTypeFair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string NetworkQualityCategoryTypeGood {
            get {
                return ResourceManager.GetString("NetworkQualityCategoryTypeGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect.
        /// </summary>
        public static string NetworkQualityCategoryTypePerfect {
            get {
                return ResourceManager.GetString("NetworkQualityCategoryTypePerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string NetworkQualityCategoryTypePoor {
            get {
                return ResourceManager.GetString("NetworkQualityCategoryTypePoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very good.
        /// </summary>
        public static string NetworkQualityCategoryTypeVeryGood {
            get {
                return ResourceManager.GetString("NetworkQualityCategoryTypeVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very poor.
        /// </summary>
        public static string NetworkQualityCategoryTypeVeryPoor {
            get {
                return ResourceManager.GetString("NetworkQualityCategoryTypeVeryPoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
    }
}
